### ISSUE TITLE
Upstream/Mainline Kernel

### ISSUE THREAD

**Issue by joaoserra** [ayourtch/nat46#16]
Hi,

Thanks for the module!

Just want to ask if you ever tried to upstream this to mainline kernel? What would be the main challenges in upstreaming this?

Thanks!

**Comment by ayourtch** [comment]
Hi Joao,

Glad you like it and if it is of any use! :-)

Once upon a time I tried to upstream a trivial fix for a somewhat obscure bug [0]; that appeared to be a time not very well spent, and that had set the initial temperature for my enthusiasm in upstreaming...

This code uses a /proc file for configuration, which I know for a fact is very frowned upon in kernel land and would make the Decision Makers unhappy, but I fundamentally disagree that ioctl is a better configuration model, and removing the /proc code from this module would have been a significant usability hit. (I am happy to agree that it may increase the attack surface due to text parsing, though).

As such to me it didn’t seem useful to even start the discussion - by now the code seems to mostly work for all the folks they use it, it’s very isolated from the rest, easy to compile in, the maintenance overhead is very low, and no one has to give up their opinions. So the status quo seems like a good optimum. :-)

But if anyone on the net feels like this code is useful enough to be in the mainline kernel and happy to do the legwork to upstream it - I will say big thank you if they succeed and buy them a coffee or beer if we ever meet :-) (I generally pop by every FOSDEM :-)

—a

0: https://patchwork.ozlabs.org/project/netdev/patch/d9679ca53d5162eaa88ac5050410e1b4fb3c2874.1471622715.git.ayourtch@gmail.com/

**Comment by joaoserra** [comment]
Understood!

Thanks for replying!
